### PR TITLE
Auto-Grouping for SSA

### PR DESCRIPTION
**Pull request by lucasplagwitz**
Hi,

I am very interested in your efficient implementation of the Singular Spectrum Analysis.
Do you ever think of an advanced grouping for the components?
You mentioned in the SSA-exmaple that

*The first subseries consists of the trend of the original time series.
The second and third subseries consist of noise.*

But should the trend not rather be a zero-like signal? 

And wouldn't it be nicer to show the possibility of decomposing an additive signal into three components (trend, seasonal, residual)?
Packages like [JULIAs-SSA](https://github.com/baggepinnen/SingularSpectrumAnalysis.jl) explicitly return trend and seasonal.
They group by a specific consideration of the eigenvalues, which in my opinion also disregard a few special cases.

My commit is only a short demo and tries to demonstrate the potential of the
SSA with a grouping inspired by [*A METHOD OF TREND EXTRACTION USING SINGULAR SPECTRUM ANALYSIS*](https://arxiv.org/abs/0804.3367). 
Also saw that the [R package](https://github.com/asl/rssa) uses a similar approach.

Are you interested in the topic of grouping SSA-components?
Then I could add tests and generalize the process.

Best regards,
Lucas

### CODE REVIEW

**Comment by lucasplagwitz** [comment]
Thank you very much for the very helpful input.  It really helps to examine things again sensibly. And your code is so much cleaner.

I have now separated out the example as a second one. I hope that my adjustments fit into your style. Otherwise, you can of course modify everything or give me feedback if you want me to change something. 

Especially for analyses like I'm currently doing, the automatic components-grouping and your SSA is very useful!

**Review by johannfaouzi — CHANGES_REQUESTED** [review]
Thank you very much! It's great, I just left a few minor remarks.

Also, please add your contribution in the [changelog](https://raw.githubusercontent.com/johannfaouzi/pyts/main/doc/changelog.rst). It will be released in version `0.13.0`. Please add your name at the end of the description (there are a couple of examples in version `0.10.0`).

**Comment by lucasplagwitz** [comment]
Absolutely right. Hopefully I didn't miss a line. Thanks for the review!

**Review by johannfaouzi — APPROVED** [review]
Perfect! Thank you very much!

**Pull request merged**
